document.getElementById('resumeForm').addEventListener('submit', function (e) {
    e.preventDefault();

    // Get form values
    const name = document.getElementById('name').value;
    const email = document.getElementById('email').value;
    const phone = document.getElementById('phone').value;
    const address = document.getElementById('address').value;
    const instagram = document.getElementById('instagram').value;
    const linkedin = document.getElementById('linkedin').value;
    const github = document.getElementById('github').value;
    const degree = document.getElementById('degree').value;
    const institution = document.getElementById('institution').value;
    const year = document.getElementById('year').value;
    const company = document.getElementById('company').value;
    const position = document.getElementById('position').value;
    const duration = document.getElementById('duration').value;
    const description = document.getElementById('description').value;
    const skills = document.getElementById('skills').value;
    const hobbies = document.getElementById('hobbies').value;
    const imageFile = document.getElementById('image').files[0];

    // Read the uploaded image
    const reader = new FileReader();
    reader.onload = function (e) {
        const imageUrl = e.target.result;

        // Show Resume Templates Section
        document.getElementById('resumeTemplates').style.display = 'block';

        // Generate 10 Different Templates
        const templateGrid = document.querySelector('.template-grid');
        templateGrid.innerHTML = '';

        for (let i = 1; i <= 10; i++) {
            const template = document.createElement('div');
            template.className = 'template';
            template.innerHTML = `
                <h3>Template ${i}</h3>
                <div class="resume-preview" id="template${i}">
                    <!-- Template content will be dynamically inserted here -->
                </div>
                <button class="download-btn" onclick="downloadTemplate(${i})">Download Template ${i}</button>
            `;

            // Generate Template Content
            const templateContent = document.createElement('div');
            templateContent.innerHTML = `
                <div class="resume-header">
                    <img src="${imageUrl}" alt="Profile Picture">
                    <h2>${name}</h2>
                    <p>${address}</p>
                    <p><strong>Email:</strong> ${email}</p>
                    <p><strong>Phone:</strong> ${phone}</p>
                    <div class="social-links">
                        ${instagram ? `<a href="${instagram}" target="_blank"><i class="fab fa-instagram"></i>Instagram</a>` : ''}
                        ${linkedin ? `<a href="${linkedin}" target="_blank"><i class="fab fa-linkedin"></i>LinkedIn</a>` : ''}
                        ${github ? `<a href="${github}" target="_blank"><i class="fab fa-github"></i>GitHub</a>` : ''}
                    </div>
                </div>
                <div class="resume-section">
                    <h3>Education</h3>
                    <p><strong>Degree:</strong> ${degree}</p>
                    <p><strong>Institution:</strong> ${institution}</p>
                    <p><strong>Year:</strong> ${year}</p>
                </div>
                <div class="resume-section">
                    <h3>Experience</h3>
                    <p><strong>Company:</strong> ${company}</p>
                    <p><strong>Position:</strong> ${position}</p>
                    <p><strong>Duration:</strong> ${duration}</p>
                    <p><strong>Description:</strong> ${description}</p>
                </div>
                <div class="resume-section">
                    <h3>Skills</h3>
                    <p>${skills}</p>
                </div>
                <div class="resume-section">
                    <h3>Hobbies</h3>
                    <p>${hobbies}</p>
                </div>
                <div class="resume-footer">
                    <p>Generated by Professional Resume Maker</p>
                </div>
            `;

            // Append Template Content
            template.querySelector('.resume-preview').appendChild(templateContent);
            templateGrid.appendChild(template);
        }
    };

    if (imageFile) {
        reader.readAsDataURL(imageFile);
    } else {
        alert('Please upload a profile picture.');
    }
});

// Download Template as Image
function downloadTemplate(templateNumber) {
    const templateElement = document.getElementById(`template${templateNumber}`);
    html2canvas(templateElement).then(canvas => {
        const link = document.createElement('a');
        link.download = `resume_template_${templateNumber}.png`;
        link.href = canvas.toDataURL('image/png');
        link.click();
    });
}